'use strict';

const qrService = require('./qr.service');

/** Minimal escaping — every value here is operator-supplied, not user-supplied. */
function esc(value) {
  return String(value ?? '').replace(
    /[&<>"']/g,
    (c) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]
  );
}

/**
 * A print-ready sheet of pack labels. Deliberately server-rendered HTML rather
 * than a PDF library: it prints identically from any browser, needs no extra
 * dependency, and can be opened straight from the API during a demo.
 *
 * The QR codes are inline SVG, so the sheet is one self-contained document
 * with no image requests and no external assets.
 */
async function renderLabelSheet({ batch, medicine, manufacturer, packs, offset, total }) {
  const labels = await Promise.all(
    packs.map(async (pack) => {
      const svg = await qrService.toSvgString(pack.serial, { width: 132 });
      return `
      <div class="label">
        <div class="qr">${svg}</div>
        <div class="meta">
          <p class="name">${esc(medicine.name)}</p>
          <p class="strength">${esc(medicine.strength)} &middot; ${esc(medicine.form)}</p>
          <p class="batch">Batch ${esc(batch.batchNo)} &middot; Exp ${esc(batch.expiresOn)}</p>
          <p class="serial">${esc(pack.serial)}</p>
        </div>
      </div>`;
    })
  );

  const shown = `${offset + 1}–${offset + packs.length} of ${total}`;

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<title>Labels · Batch ${esc(batch.batchNo)}</title>
<style>
  @page { size: A4; margin: 10mm; }
  * { box-sizing: border-box; }
  body {
    font-family: ui-sans-serif, -apple-system, "Segoe UI", Roboto, sans-serif;
    margin: 0; padding: 16px; color: #111; background: #fff;
  }
  header {
    display: flex; justify-content: space-between; align-items: baseline;
    gap: 16px; border-bottom: 2px solid #111; padding-bottom: 10px; margin-bottom: 16px;
  }
  h1 { font-size: 16px; margin: 0; }
  header .sub { font-size: 12px; color: #555; font-variant-numeric: tabular-nums; }
  .sheet {
    display: grid; grid-template-columns: repeat(auto-fill, minmax(168px, 1fr)); gap: 8px;
  }
  .label {
    border: 1px solid #bbb; border-radius: 3px; padding: 8px;
    display: flex; gap: 8px; align-items: center; break-inside: avoid; page-break-inside: avoid;
  }
  .qr { flex: 0 0 62px; line-height: 0; }
  .qr svg { width: 62px; height: 62px; display: block; }
  .meta { min-width: 0; }
  .meta p { margin: 0; line-height: 1.25; }
  .name { font-size: 10.5px; font-weight: 700; }
  .strength { font-size: 9px; color: #333; }
  .batch { font-size: 8px; color: #555; margin-top: 2px; }
  .serial {
    font-family: ui-monospace, "SF Mono", Menlo, monospace;
    font-size: 7.6px; letter-spacing: -0.2px; margin-top: 3px; word-break: break-all;
  }
  footer { margin-top: 18px; font-size: 10px; color: #666; }
  @media print { .noprint { display: none; } body { padding: 0; } }
</style>
</head>
<body>
  <header>
    <div>
      <h1>${esc(medicine.name)} ${esc(medicine.strength)} &mdash; Batch ${esc(batch.batchNo)}</h1>
      <p class="sub">${esc(manufacturer.name)} &middot; Manufactured ${esc(batch.manufacturedOn)} &middot; Expires ${esc(batch.expiresOn)}</p>
    </div>
    <p class="sub">Labels ${esc(shown)}</p>
  </header>

  <div class="sheet">${labels.join('')}</div>

  <footer>
    Every label carries a unique serial. Scanning any two identical codes is
    evidence of duplication. Generated by MedTrace AI.
  </footer>

  <p class="noprint" style="margin-top:16px;font-size:12px;color:#666">
    Press &#8984;P / Ctrl+P to print.
  </p>
</body>
</html>`;
}

module.exports = { renderLabelSheet };
